[package]
name = "next_gen_nav2_traffic"
version = "0.1.0"
edition = "2021"

[lib]
name = "nav2_traffic"

[[bin]]
path = "src/main.rs"
name = "nav2_traffic"

[dependencies]
bevy = "0.16"
bevy_ecs = "0.16"
crossflow = { version = "0.0.7", path = "../crossflow" }
futures = "0.3"
nalgebra = "0.34"
rclrs = "0.7"
thiserror = "1.0"
tokio = "1"

builtin_interfaces = "*"
geometry_msgs = "*"
nav2_msgs = "*"
rmf_prototype_msgs = "*"
std_msgs = "*"
unique_identifier_msgs = "*"